import { jsPDF } from 'jspdf';
import * as XLSX from 'xlsx';
import { GeneratedReport } from '../types';

export function exportReportToPdf(report: GeneratedReport) {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'pt',
    format: 'a4'
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 40;
  const contentWidth = pageWidth - margin * 2;
  let cursorY = margin;

  // Header Bar
  doc.setFillColor(23, 37, 84); // Navy
  doc.rect(0, 0, pageWidth, 55, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('CMPDI / COAL INDIA LIMITED — OFFICIAL REPORT DOSSIER', margin, 32);

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text('Ministry of Coal, Government of India | GeoMine Intel Platform', margin, 46);

  cursorY = 75;

  // Title
  doc.setTextColor(15, 23, 42); // Slate-900
  doc.setFontSize(15);
  doc.setFont('helvetica', 'bold');
  const titleLines = doc.splitTextToSize(report.title, contentWidth);
  doc.text(titleLines, margin, cursorY);
  cursorY += titleLines.length * 18 + 8;

  // Metadata Card
  doc.setFillColor(241, 245, 249);
  doc.roundedRect(margin, cursorY, contentWidth, 50, 4, 4, 'F');
  doc.setTextColor(71, 85, 105);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');

  doc.text(`Report Type: ${report.reportType}`, margin + 12, cursorY + 18);
  doc.text(`Period: ${report.reportingPeriod}`, margin + 12, cursorY + 34);
  doc.text(`Subsidiary: ${report.subsidiary} | Mine: ${report.mineName || 'Consolidated'}`, margin + 220, cursorY + 18);
  doc.text(`Generated By: ${report.generatedBy} | Date: ${new Date(report.createdAt).toLocaleDateString()}`, margin + 220, cursorY + 34);

  cursorY += 68;

  // Sections
  for (const sec of report.sections) {
    if (cursorY > pageHeight - 100) {
      doc.addPage();
      cursorY = margin;
    }

    doc.setTextColor(180, 83, 9); // Amber-700
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text(sec.title, margin, cursorY);
    cursorY += 16;

    doc.setTextColor(51, 65, 85);
    doc.setFontSize(9.5);
    doc.setFont('helvetica', 'normal');
    const contentLines = doc.splitTextToSize(sec.content, contentWidth);
    doc.text(contentLines, margin, cursorY);
    cursorY += contentLines.length * 13 + 12;

    if (sec.table) {
      if (cursorY > pageHeight - 120) {
        doc.addPage();
        cursorY = margin;
      }

      // Draw mini table header
      doc.setFillColor(30, 41, 59);
      doc.rect(margin, cursorY, contentWidth, 18, 'F');
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(8);
      doc.setFont('helvetica', 'bold');

      const colCount = sec.table.headers.length;
      const colWidth = contentWidth / colCount;

      sec.table.headers.forEach((h, i) => {
        doc.text(String(h).substring(0, 16), margin + i * colWidth + 4, cursorY + 12);
      });
      cursorY += 20;

      // Draw table rows
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(30, 41, 59);
      for (const row of sec.table.rows.slice(0, 8)) {
        if (cursorY > pageHeight - 40) {
          doc.addPage();
          cursorY = margin;
        }
        doc.setFillColor(248, 250, 252);
        doc.rect(margin, cursorY, contentWidth, 15, 'F');
        row.forEach((cell, i) => {
          doc.text(String(cell).substring(0, 18), margin + i * colWidth + 4, cursorY + 11);
        });
        cursorY += 17;
      }
      cursorY += 10;
    }
  }

  // Footer Disclaimer
  if (cursorY > pageHeight - 40) {
    doc.addPage();
    cursorY = margin;
  }
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text('DEMONSTRATION DATA — CMPDI / CIL SIH26023 Enterprise AI Document Intelligence Platform', margin, pageHeight - 20);

  doc.save(`${report.title.replace(/[^a-zA-Z0-9]/g, '_').substring(0, 40)}.pdf`);
}

export function exportReportToExcel(report: GeneratedReport) {
  const wb = XLSX.utils.book_new();

  // Sheet 1: Summary & Sections
  const summaryData = [
    ['CMPDI / COAL INDIA LIMITED - OFFICIAL INTELLIGENCE REPORT'],
    ['Title', report.title],
    ['Report Type', report.reportType],
    ['Period', report.reportingPeriod],
    ['Subsidiary', report.subsidiary],
    ['Mine', report.mineName || 'All Mines'],
    ['Generated By', report.generatedBy],
    ['Date Generated', report.createdAt],
    ['Data Confidence Score', `${report.summaryStats.dataConfidenceScore}%`],
    [],
    ['SECTION BREAKDOWN', 'CONTENT']
  ];

  for (const s of report.sections) {
    summaryData.push([s.title, s.content]);
  }

  const wsSummary = XLSX.utils.aoa_to_sheet(summaryData);
  XLSX.utils.book_append_sheet(wb, wsSummary, 'Executive Summary');

  // Sheet 2: Extracted Tables (if any)
  for (const s of report.sections) {
    if (s.table) {
      const tableData = [
        [s.title],
        s.table.headers,
        ...s.table.rows
      ];
      const wsTable = XLSX.utils.aoa_to_sheet(tableData);
      const sheetName = s.title.substring(0, 28).replace(/[\\/?*[\]]/g, '');
      XLSX.utils.book_append_sheet(wb, wsTable, sheetName);
    }
  }

  XLSX.writeFile(wb, `${report.title.replace(/[^a-zA-Z0-9]/g, '_').substring(0, 40)}.xlsx`);
}

export function exportReportToDocx(report: GeneratedReport) {
  let html = `
    <html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
    <head>
      <meta charset='utf-8'>
      <title>${report.title}</title>
      <style>
        body { font-family: Calibri, Arial, sans-serif; line-height: 1.5; color: #1e293b; padding: 20px; }
        h1 { color: #1e3a8a; border-bottom: 2px solid #3b82f6; padding-bottom: 6px; }
        h2 { color: #b45309; margin-top: 24px; }
        .meta-box { background: #f1f5f9; padding: 12px; border-left: 4px solid #f59e0b; margin-bottom: 20px; }
        table { border-collapse: collapse; width: 100%; margin: 16px 0; }
        th { background: #1e293b; color: white; border: 1px solid #94a3b8; padding: 8px; text-align: left; }
        td { border: 1px solid #cbd5e1; padding: 8px; font-size: 13px; }
        .disclaimer { font-size: 11px; color: #64748b; margin-top: 40px; border-top: 1px solid #e2e8f0; padding-top: 8px; }
      </style>
    </head>
    <body>
      <h1>${report.title}</h1>
      <div class="meta-box">
        <strong>CMPDI / Coal India Limited Intelligence Report</strong><br>
        <strong>Report Type:</strong> ${report.reportType} | <strong>Period:</strong> ${report.reportingPeriod}<br>
        <strong>Subsidiary:</strong> ${report.subsidiary} | <strong>Mine:</strong> ${report.mineName || 'Consolidated'}<br>
        <strong>Generated By:</strong> ${report.generatedBy} | <strong>Date:</strong> ${new Date(report.createdAt).toLocaleString()}
      </div>
  `;

  for (const sec of report.sections) {
    html += `<h2>${sec.title}</h2><p>${sec.content.replace(/\n/g, '<br>')}</p>`;
    if (sec.table) {
      html += `<table><thead><tr>`;
      sec.table.headers.forEach(h => { html += `<th>${h}</th>`; });
      html += `</tr></thead><tbody>`;
      sec.table.rows.forEach(r => {
        html += `<tr>`;
        r.forEach(c => { html += `<td>${c}</td>`; });
        html += `</tr>`;
      });
      html += `</tbody></table>`;
    }
  }

  html += `
      <div class="disclaimer">
        DEMONSTRATION DATA — NOT OFFICIAL CMPDI/CIL DATA | Generated by GeoMine Intel Platform (SIH26023)
      </div>
    </body>
    </html>
  `;

  const blob = new Blob(['\ufeff', html], {
    type: 'application/msword'
  });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${report.title.replace(/[^a-zA-Z0-9]/g, '_').substring(0, 40)}.doc`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
